export const USER_FETCH_STARTED = 'USER_FETCH_STARTED';
export const USER_FETCH_COMPLETED = 'USER_FETCH_COMPLETED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const USER_ADD_STARTED = 'USER_ADD_STARTED';
export const USER_ADD_COMPLETED = 'USER_ADD_COMPLETED';
export const USER_ADD_FAILED = 'USER_ADD_FAILED';

export const USER_REMOVE_STARTED = 'USER_REMOVE_STARTED';
export const USER_REMOVE_COMPLETED = 'USER_REMOVE_COMPLETED';
export const USER_REMOVE_FAILED = 'USER_REMOVE_FAILED';
